import type { Metadata } from "next";
import '.././globals.css';
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function HomeLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex pt-16 flex-col min-h-screen bg-gray-100">
            
            <Navbar />

            <div className="flex flex-1">
                
                <aside className="w-50 bg-gray-800 text-white hidden md:block">
                    <Sidebar />
                </aside>

                
                <main className="flex-1 p-6 bg-white shadow-lg rounded-lg m-4">
                    {children}
                </main>
            </div>

            <Footer/>
        </div>
    );
}
